<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'session' => '2025',
                'class_id' => 1, // Play
                'student_type' => 'new',
                'gender' => 'male',
                'residence_status' => 'resident',
                'name' => 'Abdullah Rahman',
                'father_name' => 'Mohammad Rahman',
                'mother_name' => 'Fatima Rahman',
                'date_of_birth' => '2010-05-15',
                'nid_birth_no' => '20105623789012',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'B+',
                'guardian_phone' => '01712345678',
                'sms_number' => '01712345678',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 2, // Nursery
                'student_type' => 'old',
                'gender' => 'male',
                'residence_status' => 'resident',
                'name' => 'Muhammad Hassan',
                'father_name' => 'Abdul Karim',
                'mother_name' => 'Ayesha Begum',
                'date_of_birth' => '2009-08-22',
                'nid_birth_no' => '20095634123456',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'A+',
                'guardian_phone' => '01823456789',
                'sms_number' => '01823456789',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 3, // First
                'student_type' => 'new',
                'gender' => 'female',
                'residence_status' => 'non-resident',
                'name' => 'Aisha Khatun',
                'father_name' => 'Md. Zakir Hossain',
                'mother_name' => 'Rashida Begum',
                'date_of_birth' => '2008-12-10',
                'nid_birth_no' => '20086745890123',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'O+',
                'guardian_phone' => '01934567890',
                'sms_number' => '01934567890',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 7, // Nazira
                'student_type' => 'old',
                'gender' => 'male',
                'residence_status' => 'resident',
                'name' => 'Ibrahim Ali',
                'father_name' => 'Hafiz Nurul Islam',
                'mother_name' => 'Rukhsana Parvin',
                'date_of_birth' => '2007-03-25',
                'nid_birth_no' => '20076712345678',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'AB+',
                'guardian_phone' => '01645678901',
                'sms_number' => '01645678901',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 8, // Hifzul Quran
                'student_type' => 'new',
                'gender' => 'female',
                'residence_status' => 'non-resident',
                'name' => 'Hafsa Rahman',
                'father_name' => 'Dr. Aminul Islam',
                'mother_name' => 'Salma Khatun',
                'date_of_birth' => '2011-07-14',
                'nid_birth_no' => '20117890123456',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'B-',
                'guardian_phone' => '01756789012',
                'sms_number' => '01756789012',
                'is_active' => true,
            ],
            // Additional students
            [
                'session' => '2025',
                'class_id' => 1, // Play
                'student_type' => 'new',
                'gender' => 'female',
                'residence_status' => 'non-resident',
                'name' => 'Maryam Siddique',
                'father_name' => 'Siddique Ahmed',
                'mother_name' => 'Nusrat Jahan',
                'date_of_birth' => '2010-09-20',
                'nid_birth_no' => '20109876543210',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'O+',
                'guardian_phone' => '01612345678',
                'sms_number' => '01612345678',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 2, // Nursery
                'student_type' => 'new',
                'gender' => 'male',
                'residence_status' => 'non-resident',
                'name' => 'Yusuf Khan',
                'father_name' => 'Rafiq Khan',
                'mother_name' => 'Amina Khan',
                'date_of_birth' => '2009-03-15',
                'nid_birth_no' => '20093456789123',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'A-',
                'guardian_phone' => '01723456789',
                'sms_number' => '01723456789',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 3, // First
                'student_type' => 'old',
                'gender' => 'male',
                'residence_status' => 'resident',
                'name' => 'Omar Farooq',
                'father_name' => 'Abdul Farooq',
                'mother_name' => 'Khadija Begum',
                'date_of_birth' => '2008-06-18',
                'nid_birth_no' => '20086543219876',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'B+',
                'guardian_phone' => '01834567890',
                'sms_number' => '01834567890',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 4, // Second
                'student_type' => 'new',
                'gender' => 'female',
                'residence_status' => 'resident',
                'name' => 'Zainab Hossain',
                'father_name' => 'Kamal Hossain',
                'mother_name' => 'Taslima Akter',
                'date_of_birth' => '2007-11-05',
                'nid_birth_no' => '20077654321098',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'AB-',
                'guardian_phone' => '01945678901',
                'sms_number' => '01945678901',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 4, // Second
                'student_type' => 'old',
                'gender' => 'male',
                'residence_status' => 'non-resident',
                'name' => 'Bilal Ahmed',
                'father_name' => 'Shahid Ahmed',
                'mother_name' => 'Sabrina Sultana',
                'date_of_birth' => '2007-04-12',
                'nid_birth_no' => '20074567890123',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'O-',
                'guardian_phone' => '01656789012',
                'sms_number' => '01656789012',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 5, // Third
                'student_type' => 'new',
                'gender' => 'female',
                'residence_status' => 'resident',
                'name' => 'Fatima Zahra',
                'father_name' => 'Mahmud Hassan',
                'mother_name' => 'Rehana Khatun',
                'date_of_birth' => '2006-08-30',
                'nid_birth_no' => '20068901234567',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'A+',
                'guardian_phone' => '01767890123',
                'sms_number' => '01767890123',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 5, // Third
                'student_type' => 'old',
                'gender' => 'male',
                'residence_status' => 'resident',
                'name' => 'Hamza Malik',
                'father_name' => 'Tariq Malik',
                'mother_name' => 'Jasmine Akter',
                'date_of_birth' => '2006-12-22',
                'nid_birth_no' => '20069012345678',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'B-',
                'guardian_phone' => '01878901234',
                'sms_number' => '01878901234',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 6, // Fourth
                'student_type' => 'new',
                'gender' => 'male',
                'residence_status' => 'non-resident',
                'name' => 'Sulaiman Haque',
                'father_name' => 'Moinul Haque',
                'mother_name' => 'Nazma Begum',
                'date_of_birth' => '2005-05-17',
                'nid_birth_no' => '20055678901234',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'AB+',
                'guardian_phone' => '01989012345',
                'sms_number' => '01989012345',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 6, // Fourth
                'student_type' => 'old',
                'gender' => 'female',
                'residence_status' => 'resident',
                'name' => 'Ruqayyah Islam',
                'father_name' => 'Shafiullah Islam',
                'mother_name' => 'Parvin Sultana',
                'date_of_birth' => '2005-02-28',
                'nid_birth_no' => '20052345678901',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'O+',
                'guardian_phone' => '01690123456',
                'sms_number' => '01690123456',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 7, // Nazira
                'student_type' => 'new',
                'gender' => 'female',
                'residence_status' => 'non-resident',
                'name' => 'Sumaya Rahman',
                'father_name' => 'Ataur Rahman',
                'mother_name' => 'Hosne Ara',
                'date_of_birth' => '2007-10-08',
                'nid_birth_no' => '20071234567890',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'A-',
                'guardian_phone' => '01701234567',
                'sms_number' => '01701234567',
                'is_active' => true,
            ],
            [
                'session' => '2025',
                'class_id' => 8, // Hifzul Quran
                'student_type' => 'old',
                'gender' => 'male',
                'residence_status' => 'resident',
                'name' => 'Talha Bin Zubair',
                'father_name' => 'Hafiz Zubair Ahmed',
                'mother_name' => 'Sumayya Khatun',
                'date_of_birth' => '2011-01-25',
                'nid_birth_no' => '20112345678901',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'B+',
                'guardian_phone' => '01812345678',
                'sms_number' => '01812345678',
                'is_active' => true,
            ],
            // Some inactive students for testing
            [
                'session' => '2024',
                'class_id' => 3, // First
                'student_type' => 'old',
                'gender' => 'male',
                'residence_status' => 'non-resident',
                'name' => 'Idris Ali (Inactive)',
                'father_name' => 'Yusuf Ali',
                'mother_name' => 'Rahima Begum',
                'date_of_birth' => '2008-07-15',
                'nid_birth_no' => '20087890123456',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'O+',
                'guardian_phone' => '01923456789',
                'sms_number' => '01923456789',
                'is_active' => false,
            ],
            [
                'session' => '2024',
                'class_id' => 5, // Third
                'student_type' => 'old',
                'gender' => 'female',
                'residence_status' => 'resident',
                'name' => 'Safiya Khatun (Inactive)',
                'father_name' => 'Ibrahim Khalil',
                'mother_name' => 'Laila Akter',
                'date_of_birth' => '2006-11-30',
                'nid_birth_no' => '20068901234560',
                'nationality' => 'Bangladeshi',
                'blood_group' => 'A+',
                'guardian_phone' => '01634567890',
                'sms_number' => '01634567890',
                'is_active' => false,
            ],
        ];

        foreach ($students as $student) {
            Student::create($student);
        }
    }
}
