version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_NAME=MadrasaManagement
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000

      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=madrasa_db
      - DB_USERNAME=madrasa_user
      - DB_PASSWORD=madrasa_password

      - LOG_CHANNEL=stack
      - LOG_LEVEL=error

      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=database
      - SESSION_DRIVER=file
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      - madrasa-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=madrasa_db
      - MYSQL_USER=madrasa_user
      - MYSQL_PASSWORD=madrasa_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - madrasa-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=madrasa_user
      - PMA_PASSWORD=madrasa_password
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - madrasa-network

volumes:
  mysql_data:

networks:
  madrasa-network:
    driver: bridge